services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # Common environment variables for all services
  booking-service:
    build:
      context: .
      dockerfile: booking-service/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_ADDRESS: kafka:9092
    ports:
      - "8080:8080"

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_ADDRESS: kafka:9092
    ports:
      - "8081:8081"

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_ADDRESS: kafka:9092
    ports:
      - "8082:8082"